### ISSUE TITLE
Pretrained models URL not working

### ISSUE THREAD

**Issue by prasannasagar** [Rongjiehuang/GenerSpeech#15]
Hi this model pipeline is amazing. However, the URL given for pertained models is not working now. 

Also, earlier when it worked there were issues like different configuration in yaml files and checkpoint files.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/124148277/228224334-1f6e5421-ab8d-480f-89f1-333db057875d.png">

Thanks a ton!

**Comment by Rongjiehuang** [comment]
Hi, the URL has been updated

**Comment by sultanovazamat** [comment]
@Rongjiehuang still invalid link. Just checked.

**Comment by Rongjiehuang** [comment]
Try it again. It should be available.

**Comment by sultanovazamat** [comment]
Here is the link: https://zjueducn-my.sharepoint.com/:f:/g/personal/rongjiehuang_zju_edu_cn/EkewjLpkfoJBgOBr5F_59EgBy_twkdZ1yTmtL4HafBJqwg?e=hu671b

but still not available, the same output as @prasannasagar showed.

**Comment by prasannasagar** [comment]
The updated link is https://zjueducn-my.sharepoint.com/:f:/g/personal/rongjiehuang_zju_edu_cn/EicJK9PNylNEl5fUlFRBExIBzK2MmKjuGSbt8n4HztMv6A?e=h6r8vM

This is working.

Thanks a lot for the super fast response @Rongjiehuang

**Comment by sultanovazamat** [comment]
@Rongjiehuang only the statistical files' link is not valid, others are ok.
