### ISSUE TITLE
bug of inference

### ISSUE THREAD

**Issue by JJun-Guo** [Rongjiehuang/GenerSpeech#2]
Traceback (most recent call last):
  File "inference/GenerSpeech.py", line 2, in <module>
    from inference.base_tts_infer import BaseTTSInfer
ModuleNotFoundError: No module named 'inference'

**Comment by UstymKhaburskiy** [comment]
Add this to the inference/GenerSpeech.py file:
import sys
sys.path.append('../GenerSpeech')
