### ISSUE TITLE
the link for the pre-trained weights has expired

### ISSUE THREAD

**Issue by meriamOu** [Rongjiehuang/GenerSpeech#20]
thank you for sharing this great work. Could you please share the weights. The link has expired.
thank you!!

**Comment by MisakaMikoto96** [comment]
same.
Could u please update? THX ；-）

**Comment by Rongjiehuang** [comment]
please visit https://huggingface.co/spaces/Rongjiehuang/GenerSpeech/tree/main/checkpoints
