### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by JJun-Guo** [Rongjiehuang/GenerSpeech#3]
FileNotFoundError: [Errno 2] No such file or directory: '/home/junjun.guo/.cache/huggingface/hub/models--facebook--wav2vec2-base-960h/refs/main'

**Comment by JJun-Guo** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/junjun.guo/.cache/huggingface/hub/models--facebook--wav2vec2-base-960h/refs/main'

请问 transformers的版本是什么呢？

**Comment by Rongjiehuang** [comment]
Hi, you may check out your local cache and re-download it from scratch
