### ISSUE TITLE
MFA inference problem

### ISSUE THREAD

**Issue by edwin-19** [Rongjiehuang/GenerSpeech#5]
Hi can i ask if your using v1 of mfa, i tried running the inference but when it comes to the MFA portion it generates only an empty txt file, no text grid file at all

it would be great if you can provide the MFA instructions

**Comment by Rongjiehuang** [comment]
Hi, please install MFA according to https://montreal-forced-aligner.readthedocs.io/en/latest/getting_started.html via:
`conda config --add channels  conda-forge` 
`conda install montreal-forced-aligner`
