### ISSUE TITLE
None achademical but a general question here 

### ISSUE THREAD

**Issue by lucasjinreal** [Rongjiehuang/GenerSpeech#7]
Hi, does it able to synethsis Tom Cruise voice with just only the pretrained model and a sample real voice of his own?

**Comment by Rongjiehuang** [comment]
Yes, it is able to do so, and it is pretty cool. At the same time, please pay attention to the disclaimer `https://github.com/Rongjiehuang/GenerSpeech#disclaimer` in advanced.
